language: r
latex: false
pandoc: false
addons:
  apt:
    packages:
      - libudunits2-dev
      - gdal-bin
      - libgdal1-dev
cache:
  directories:
    - $HOME/.local/share/renv
    - $TRAVIS_BUILD_DIR/renv/library
  packages: true

r_binary_packages:
  - rgdal

git: 
  depth: 5
  submodules: false

before_install:
  - git config --global user.email "${GIT_EMAIL}"
  - git config --global user.name "${GIT_UN}"

script:
  - Rscript -e "renv::restore()"
  - Rscript scripts/pull_ncov.R
  # - Rscript scripts/pull_map.R # No longer needed, timeout issues

after_success:
  - git add -A
  - git commit -m "Data Updated."
  - git push -q https://${GH_KEY}@github.com/beansrowning/travis-ncov.git HEAD:master
