language: r
sudo: false
latex: false
pandoc: false
cache:
  packages: true

git: 
  depth: 5
  submodules: false

before_install:
  - git config --global user.email "${GIT_EMAIL}
  - git config --global user.name "${GIT_UN}"

script:
  - Rscript scripts/run.R

after_success:
  - git add -A
  - git commit -m"travis update"
  - git push -q https://${GH_KEY}@github.com/beansrowning/travis-ncov.git HEAD:master
